# Generated by Django 6.0.6 on 2026-06-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Tolú Turismo', max_length=120, verbose_name='nombre del sitio')),
                ('eslogan', models.CharField(blank=True, max_length=200, verbose_name='eslogan')),
                ('logo_url', models.URLField(blank=True, max_length=600, verbose_name='URL del logo')),
                ('telefono_whatsapp', models.CharField(blank=True, help_text='Número en formato internacional sin signos, ej. 573001234567.', max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('meta_description', models.CharField(blank=True, help_text='Descripción SEO usada cuando una página no define la suya.', max_length=300, verbose_name='meta description por defecto')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('x', 'X (Twitter)')], max_length=20, verbose_name='plataforma')),
                ('url', models.URLField(max_length=600, verbose_name='URL')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'red social',
                'verbose_name_plural': 'redes sociales',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
