# Generated by Django 6.0.6 on 2026-06-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='hero_intervalo_segundos',
            field=models.PositiveIntegerField(default=6, help_text='Cada cuántos segundos rota la imagen del hero del home.', verbose_name='intervalo del hero (segundos)'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(help_text='Foto horizontal, ≥1920px de ancho.', max_length=600, verbose_name='URL de la imagen')),
                ('titulo', models.CharField(blank=True, help_text='Texto grande sobre la imagen (opcional).', max_length=120, verbose_name='título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='subtítulo')),
                ('cta_texto', models.CharField(blank=True, max_length=40, verbose_name='texto del botón')),
                ('cta_url', models.URLField(blank=True, help_text='Se usa solo si no eliges un servicio.', max_length=600, verbose_name='o URL manual')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('activo', models.BooleanField(default=True, verbose_name='activo (entra en la rotación)')),
                ('servicio', models.ForeignKey(blank=True, help_text='Si eliges un servicio, el botón lleva a su página de detalle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_slides', to='servicios.servicio', verbose_name='enlazar a un servicio')),
            ],
            options={
                'verbose_name': 'imagen del hero',
                'verbose_name_plural': 'imágenes del hero',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
