# Generated by Django 6.0.6 on 2026-06-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('tipo', models.CharField(choices=[('hotel', 'Hotel'), ('lancha', 'Lancha / Tour')], db_index=True, max_length=10, verbose_name='tipo')),
                ('descripcion_corta', models.CharField(help_text='Texto breve para las tarjetas del catálogo.', max_length=180, verbose_name='descripción corta')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio')),
                ('unidad_precio', models.CharField(choices=[('por_noche', 'por noche'), ('por_persona', 'por persona'), ('por_recorrido', 'por recorrido'), ('por_dia', 'por día')], default='por_noche', max_length=15, verbose_name='unidad de precio')),
                ('lugar', models.CharField(help_text='Zona de Tolú o destino del tour (ej. Playa El Francés, Islas de San Bernardo).', max_length=140, verbose_name='lugar / ubicación')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='longitud')),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidad')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado en el home')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='visible en el sitio')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-destacado', '-creado'],
                'indexes': [models.Index(fields=['tipo', 'activo'], name='servicios_s_tipo_b583a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600, verbose_name='URL de la imagen')),
                ('titulo', models.CharField(help_text='Describe la imagen (accesibilidad y SEO).', max_length=160, verbose_name='título / texto alternativo')),
                ('es_portada', models.BooleanField(default=False, verbose_name='usar como portada')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Enlace de YouTube o Vimeo.', max_length=600, verbose_name='URL del video')),
                ('titulo', models.CharField(blank=True, max_length=160, verbose_name='título')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
