# Generated by Django 6.0.6 on 2026-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='unidad_precio',
            field=models.CharField(blank=True, choices=[('por_noche', 'por noche'), ('por_persona', 'por persona'), ('por_recorrido', 'por recorrido'), ('por_dia', 'por día')], default='por_noche', max_length=15, verbose_name='unidad de precio'),
        ),
    ]
