# Generated by Django 6.0.6 on 2026-06-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_precio_alter_servicio_unidad_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Déjalo vacío si el precio es variable: el sitio invitará a consultar por WhatsApp.', max_digits=12, null=True, verbose_name='precio'),
        ),
    ]
